### ISSUE TITLE
PGP web gui

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/eth-kvstore#13]
An app to encrypt messages using eth-kvstore as a pki.

- [ ] Allow the user to generate a public and private key. The private key should be a file that they store locally
- [ ] Allow users to register public pgp keys with a specific eth address in kv store
- [ ] Allow users to encrypt a web form string for a given eth address
- [ ] Allow users to use local private key to decrypt a web form string

## Bonus
- [ ] Allow users to encrypt with multiple eth keys

As always please make sure to add plenty of documentation and testing.

**Comment by spiritbroski** [comment]
hello i would like to try to create this

**Comment by posix4e** [comment]
Wanna reach out on tech discussion on discord for the details and your plan
